Update DocumentationGenerator.php
ErrorException: Method ReflectionMethod::setAccessible() is deprecated since 8.5, as it has no effect since PHP 8.1 in /var/www/html/vendor/romanzipp/laravel-model-doc/src/Services/DocumentationGenerator.php:275